Add a dockerfile
zachbr/Dis4IRC pull request #56
Opened 2021-06-03 12:36 UTC by lucyy-mc

Adds a Dockerfile to allow running Dis4IRC in a Docker container. I'm more than happy to publish this on docker hub when it's finished.

This PR is still a draft, there are some issues that I need to fix.

To use, clone the repo,  `docker build .` then `docker run -v /path/to/config.hocon:/srv/config.hocon <container id>`.

Fixes #55

2021-06-03 23:06 UTC, zachbr commented
Hi, thanks for taking a look at this.

My main concern so far is that it looks like it always pulls down the master branch and compiles from that. While I do try and keep master in a state where it is always running, it seems less than ideal to always be distributing that via docker. I can understand that it could also be tedious to keep bumping the docker image on every minor release as well. Is there perhaps a way to make it always fetch the latest release tag and compile that instead?

It seems like there are ways to get the latest git tag from the git CLI, is that something that would fit better do you think?

2021-06-03 23:07 UTC, kashike requested changes

2021-06-03 23:07 UTC, kashike commented on Dockerfile
> +COPY --from=BUILD /build/libs/Dis4IRC-*.jar /srv/dis4irc.jar
This will cause problems if we have more than one JAR - try to make this more specific.

2021-06-04 06:48 UTC, lucyy-mc commented
> My main concern so far is that it looks like it always pulls down the master branch and compiles from that. 

The dockerfile itself isn't responsible for obtaining source, it just builds what you have locally. Realistically, for deployment, you'd use a CI server and build on release (which I'm more than happy to set up on my TC instance if needed).

2021-06-05 02:25 UTC, zachbr commented
Thanks. That makes sense but I’m (obviously) not overly familiar with docker. I suppose I should’ve made that connection myself given the lack of any “pull” action in the docker file.

I have my own TC instance we would probably want to use to maintain releases, but I’d love to see a test version using your instance if it isn’t too much trouble.

kash’s comments about multiple jars should probably be addressed as well. Right now there is always one shaded artifact on build but I imagine we shouldn’t necessarily assume that either. As a docker noob I look forward to your input.

2021-06-05 07:28 UTC, lucyy-mc commented
> I’d love to see a test version using your instance if it isn’t too much trouble.

Yeah that's fine, I can do that.

> kash’s comments about multiple jars should probably be addressed as well.

I am trying my best here, but Docker is notoriously bad for getting the output of commands into variables that I could then use to get the project version. I have an idea for a shell workaround, I'll try it and let you know.

2021-06-05 11:29 UTC, lucyy-mc commented
Turns out you don't even need a CI server, docker hub will do it all for you. This config will create images any time a new tag is created, creating a Docker tag for it, and also maintains the `unstable` tag with the latest commit.
![image](https://user-images.githubusercontent.com/35287819/120890305-ac1c5a80-c5f9-11eb-8a6b-acd5bd209a19.png)

2021-06-05 18:49 UTC, lucyy-mc commented
https://hub.docker.com/repository/docker/lucyymc/dis4irc

2024-09-19 20:43 UTC, raws1 commented
Any chance you'd pick this back up @lucyydotp?

2024-09-19 21:22 UTC, lucyydotp commented
> Any chance you'd pick this back up @lucyydotp?

Gonna be honest with ya I have not used this since I made this pr more than 3 years ago :’)

I see no reason why the dockerfile I wrote would’ve broken though, I can pull quickly to test if wanted

2024-11-01 05:53 UTC, ilyagr commented
I'm not a Docker expert, but here's a Dockerfile that seems to work fine for me. It assumes you downloaded the `jar` file for Dis4IRC. (I considered putting a `wget` command inside the Dockerfile, but decided that would only make it less reliable).

```dockerfile
FROM eclipse-temurin:23-jre-alpine
RUN mkdir /opt/app
COPY Dis4IRC-1.6.3.jar /opt/app
COPY config.hocon /opt/app
WORKDIR /opt/app
CMD ["java", "-jar", "Dis4IRC-1.6.3.jar"]
```

It's based on the docs from https://hub.docker.com/_/eclipse-temurin/, see there for many, many more options. In particular, if you want to do anything fancier, you might want the normal `eclipse-temurin:23` image which is a bit larger (a whole 250MB, I think, the horror!) but includes Debian, `apk`, and a JDK instead of just a Java runtime.

2025-05-10 21:22 UTC, closed without merging

2025-05-10 21:31 UTC, zachbr commented
I've (finally) added this after trying to better understand containers and the proper way to do this. It's diverged a bit but seems to work fairly well to my understanding. We are bundling the jar in the provided container so that we get proper versioning, immutability, rollback, etc. I suspect that may be annoying for someone who'd prefer to track `master` directly but to my understanding it's the best practice. A `latest` tag exists that will be built on every commit, as well as versioned tags for each release build.

I didn't use this PR directly so I didn't merge it - but I think it's fair to give both @lucyydotp and @ilyagr credit for bringing this up and pointing me in the right direction so your names are mentioned in the commit (for whatever that's worth). A special thanks to you both.

If there are any comments, suggestions, etc. please feel free to reply here, open a new issue, etc. as you prefer.